Repository Nautilus-Cyberneering/nautilus-librarian, pull requests merged in 2021-12, with the labels that each got.

#13 Import CODE_OF_CONDUCT and CONTRIBUTING from library
  .cspell.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement

#37 Issue 34 - Licensing Documentation
  .cspell.json
  LICENSE
  licensing/agpl-3.0.md
  licensing/cc-by-sa.md
  licensing/contributor_agreement_v01.md
  licensing/file_header_agplv3.txt
  licensing/old_commits/cc0.md
  licensing/old_commits/mit-0.md
Labels: documentation

#25 Issue 24 dvc api wrapper
  .cspell.json
  src/nautilus_librarian/mods/console/domain/utils.py
  src/nautilus_librarian/mods/dvc/domain/api.py
  tests/conftest.py
  tests/test_nautilus_librarian/test_mods/test_dvc/test_domain/test_api.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_auto_commit_images.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_gold_images_processing.py
Labels: enhancement

#51 Add .DS_Store to gitignore file
  .gitignore
Labels: enhancement

#54 New 'validate file paths' action in Gold Images Processing command
  src/nautilus_librarian/domain/validate_filepaths.py
  src/nautilus_librarian/mods/dvc/domain/utils.py
  src/nautilus_librarian/typer/commands/workflows/actions/action_result.py
  src/nautilus_librarian/typer/commands/workflows/actions/validate_filenames.py
  src/nautilus_librarian/typer/commands/workflows/actions/validate_filepaths_action.py
  src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py
  tests/test_nautilus_librarian/test_mods/test_dvc/test_domain/test_utils.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_action_result.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_message.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_validate_filepaths_action.py
Labels: enhancement

#58 Remove deprecated DVC functions
  src/nautilus_librarian/mods/dvc/domain/api.py
  src/nautilus_librarian/mods/dvc/domain/utils.py
  src/nautilus_librarian/typer/commands/workflows/actions/auto_commit_base_images.py
  src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py
  tests/test_nautilus_librarian/test_mods/test_dvc/test_domain/test_api.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_dvc_pull_action.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_gold_images_processing.py
Labels: refactor
