Repository Nautilus-Cyberneering/nautilus-librarian, pull requests merged in 2022-01, with the labels that each got.

#60 Refactor: extract class DvcDiffParser
  src/nautilus_librarian/mods/dvc/domain/dvc_diff_parser.py
  src/nautilus_librarian/mods/dvc/domain/utils.py
  tests/test_nautilus_librarian/test_mods/test_dvc/test_domain/test_dvc_diff_parser.py
Labels: refactor

#63 Setup Semgrep
  .cspell.json
  .github/workflows/semgrep.yml
Labels: security

#67 Issue 64 create image size validation action
  .cspell.json
  .github/workflows/test-workflow-integration-using-pip.yml
  .github/workflows/test-workflow-integration-using-poetry.yml
  .github/workflows/test.yml
  src/nautilus_librarian/mods/libvips/domain/utils.py
  src/nautilus_librarian/mods/libvips/domain/validate_image_dimensions.py
  src/nautilus_librarian/typer/commands/workflows/actions/validate_images_dimensions_action.py
  src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py
  tests/test_nautilus_librarian/test_mods/test_libvips/fixtures/libvips_fixtures.py
  tests/test_nautilus_librarian/test_mods/test_libvips/fixtures/test_image.tif
  tests/test_nautilus_librarian/test_mods/test_libvips/test_domain/test_utils.py
  tests/test_nautilus_librarian/test_mods/test_libvips/test_domain/test_validate_image_dimensions.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_validate_images_dimensions_action.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_gold_images_processing.py
Labels: enhancement

#78 Issue 77 fix rename handling
  src/nautilus_librarian/mods/dvc/domain/api.py
  src/nautilus_librarian/typer/commands/workflows/actions/rename_base_images_action.py
  src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py
  tests/test_nautilus_librarian/test_mods/test_dvc/test_domain/test_api.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/fixtures/workflows_fixtures.py
  tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_rename_base_images_action.py
Labels: bug
